/**
 * Pure report renderer.
 * Takes an Analysis object and returns a clean Markdown string.
 * No side effects, no API calls — easy to test.
 */

import { Analysis } from "./types.js";

/**
 * Render a bulleted list from an array of strings.
 */
function bullets(items: string[]): string {
  return items.map((item) => `- ${item}`).join("\n");
}

/**
 * Render the per-ad insights table.
 * Truncates long hook/copy text to keep the table readable.
 */
function insightsTable(analysis: Analysis): string {
  const header =
    "| # | Page | Hook | Angle | Offer | Format |\n" +
    "|---|------|------|-------|-------|--------|";

  const rows = analysis.ad_insights.map((insight, idx) => {
    const hook = insight.hook.length > 60
      ? insight.hook.slice(0, 57) + "..."
      : insight.hook;
    const angle = insight.angle.length > 30
      ? insight.angle.slice(0, 27) + "..."
      : insight.angle;
    const offer = insight.offer.length > 30
      ? insight.offer.slice(0, 27) + "..."
      : insight.offer;

    return `| ${idx + 1} | ${insight.page_name} | ${hook} | ${angle} | ${offer} | ${insight.format} |`;
  });

  return [header, ...rows].join("\n");
}

/**
 * Main render function.
 * @param analysis - The fully populated Analysis object
 * @returns        - A Markdown string suitable for printing or writing to a file
 */
export function renderReport(analysis: Analysis): string {
  const now = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

  return `# ad-scout Report: ${analysis.brand}

> Generated by [ad-scout](https://github.com/liamssbusiness/ad-scout) on ${now}
> Ads analyzed: **${analysis.ads_analyzed}** | Pipeline: Haiku (extract) → Sonnet (synthesize)

---

## Executive Summary

${analysis.summary}

---

## Strategic Breakdown

### Common Hooks
${bullets(analysis.common_hooks)}

### Dominant Angles
${bullets(analysis.dominant_angles)}

### Offer & CTA Patterns
${bullets(analysis.offer_patterns)}

### Format Mix
${bullets(analysis.format_mix)}

---

## Gaps & Opportunities

${bullets(analysis.gaps)}

---

## Recommendations

${analysis.recommendations.map((rec, i) => `**${i + 1}.** ${rec}`).join("\n\n")}

---

## Per-Ad Breakdown

${insightsTable(analysis)}

---

*Built with [ad-scout](https://github.com/liamssbusiness/ad-scout) — open-source competitor ad intelligence for marketers.*
`;
}
